[tool.poetry]
name = "tdameritrade-cli"
version = "0.2.0"
description = "A CLI built on top of the tdameritrade-client API library"
authors = ["Joe Castagneri <jcastagneri@gmail.com>"]
readme = "README.md"
url = "https://gitlab.com/tdameritrade-tools/tdameritrade-cli"
repository = "https://gitlab.com/tdameritrade-tools/tdameritrade-cli"
documentation = "https://tdameritrade-cli.readthedocs.io/en/latest/?#"
classifiers = [
        "Programming Language :: Python :: 3.6",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: MacOS"
]

[tool.poetry.dependencies]
python = "^3.6"
tdameritrade-client = "^0.3"
click = "^7.0"
pyexcel-ods = "^0.5.6"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
sphinx = "^2.0"
sphinx_rtd_theme = "^0.4.3"
pytest-cov = "^2.6"

[tool.poetry.scripts]
tda-cli = 'tdameritrade_cli.cli:driver'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
