[tool.poetry]
name = "mattes-allegro-pl"
version = "0.5.1"
description = "Python client for Allegro.pl API"
authors = ["Raphael Krupinski"]
license = 'MIT'
packages=[{include='allegro_pl', from='src'}]

[tool.poetry.dependencies]
python = "^3.7"
allegro-pl-rest-api = "^2019.3"
oauthlib = "^3.0"
requests-oauthlib = "^1.2"
tenacity = "^5.0.4"
zeep = "^3.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
